/* Logos des chaînes introduites par le scan instrumental du 19 juillet 2026.
   Unavatar renvoie l'avatar YouTube réel à partir de l'identifiant de chaîne. */
window.YT_CHANNEL_AVATARS=window.YT_CHANNEL_AVATARS||{channels:{},videos:{}};
window.YT_CHANNEL_AVATARS.channels=window.YT_CHANNEL_AVATARS.channels||{};
Object.assign(window.YT_CHANNEL_AVATARS.channels,{
  "UCzYB0J1KFFo5P2EAiRuwdJw":"https://unavatar.io/youtube/UCzYB0J1KFFo5P2EAiRuwdJw?fallback=false",
  "UCSaw8c5rKbUnSvFTHYYOimQ":"https://unavatar.io/youtube/UCSaw8c5rKbUnSvFTHYYOimQ?fallback=false",
  "UCgrnOgTDK894aZBBY9uytEQ":"https://unavatar.io/youtube/UCgrnOgTDK894aZBBY9uytEQ?fallback=false",
  "UC_oeV58JVVXtxxs09oK1dLg":"https://unavatar.io/youtube/UC_oeV58JVVXtxxs09oK1dLg?fallback=false",
  "UCSiGiflTMqoEV-MjTWYy7pg":"https://unavatar.io/youtube/UCSiGiflTMqoEV-MjTWYy7pg?fallback=false",
  "UCIAqhzUWu55IDxrRN9SpiFg":"https://unavatar.io/youtube/UCIAqhzUWu55IDxrRN9SpiFg?fallback=false",
  "UCvI-KZbebDSQhr8jYYV5E1w":"https://unavatar.io/youtube/UCvI-KZbebDSQhr8jYYV5E1w?fallback=false",
  "UCfd4UTXGfbcBS96KPBrkBbg":"https://unavatar.io/youtube/UCfd4UTXGfbcBS96KPBrkBbg?fallback=false",
  "UCTx1AueVh8rLQBB8tDXZQgw":"https://unavatar.io/youtube/UCTx1AueVh8rLQBB8tDXZQgw?fallback=false",
  "UC_fHoylRU1AZCOIA_pkEvJw":"https://unavatar.io/youtube/UC_fHoylRU1AZCOIA_pkEvJw?fallback=false",
  "UCBnYtVHAPIqWedknRsQIIsw":"https://unavatar.io/youtube/UCBnYtVHAPIqWedknRsQIIsw?fallback=false",
  "UCTVaZFdiiOK6YvauN1zeklw":"https://unavatar.io/youtube/UCTVaZFdiiOK6YvauN1zeklw?fallback=false",
  "UCh6__AiN03OvIbN8IKMb1cA":"https://unavatar.io/youtube/UCh6__AiN03OvIbN8IKMb1cA?fallback=false",
  "UCdqaVzVwqlSd7CgsyS0YAaA":"https://unavatar.io/youtube/UCdqaVzVwqlSd7CgsyS0YAaA?fallback=false",
  "UCyQKoLtVor_r1OCOBgeOofQ":"https://unavatar.io/youtube/UCyQKoLtVor_r1OCOBgeOofQ?fallback=false",
  "UCke8kHyaOQ7ywFpHgzAMfMA":"https://unavatar.io/youtube/UCke8kHyaOQ7ywFpHgzAMfMA?fallback=false",
  "UCAOvtf1YR5FiVxQ0o6Iah8A":"https://unavatar.io/youtube/UCAOvtf1YR5FiVxQ0o6Iah8A?fallback=false",
  "UCKpKB_9KYpiGVmIJECrEc9w":"https://unavatar.io/youtube/UCKpKB_9KYpiGVmIJECrEc9w?fallback=false",
  "UCQC3hiAGYHpui2wkaSa3AXw":"https://unavatar.io/youtube/UCQC3hiAGYHpui2wkaSa3AXw?fallback=false",
  "UCZGP5NGagTmkkjIhRCjZq7Q":"https://unavatar.io/youtube/UCZGP5NGagTmkkjIhRCjZq7Q?fallback=false",
  "UCFLr5iyUrhHMmIQKYimzLfg":"https://unavatar.io/youtube/UCFLr5iyUrhHMmIQKYimzLfg?fallback=false",
  "UCHAJM6GGM4WCEk8o8-gLtBg":"https://unavatar.io/youtube/UCHAJM6GGM4WCEk8o8-gLtBg?fallback=false",
  "UCYWTtw3sQf2DuMQkL1ASM0Q":"https://unavatar.io/youtube/UCYWTtw3sQf2DuMQkL1ASM0Q?fallback=false"
});
